/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;

import org.junit.Test;
import static org.junit.Assert.*;

public class CommandAnalyzerTest {
    @Test public void testAnalyze() {
        CommandAnalyzer an = new CommandAnalyzer();
        Command c1 = an.analyze("show");
        assertEquals("show", c1.getName());
        assertEquals("", c1.getArg());

        Command c2 = an.analyze("add あああ");
        assertEquals("add", c2.getName());
        assertEquals("あああ", c2.getArg());

        Command c3 = an.analyze("add ああ あ");
        assertEquals("add", c3.getName());
        assertEquals("ああ あ", c3.getArg());
    }
}
