/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;

import org.junit.Test;
import static org.junit.Assert.*;

public class TaskModelTest {
    @Test public void testAdd() {
        TaskModel model = new TaskModel();
        model.add("あああ");
        assertEquals("あああ", model.getAll().get(0).getText());
        assertEquals(1, model.getAll().get(0).getId());
    }

    @Test public void testDelete() {
        TaskModel model = new TaskModel();
        model.add("あああ");
        model.add("いいい");
        model.delete(1);
        assertEquals("いいい", model.getAll().get(0).getText());
        assertEquals(2, model.getAll().get(0).getId());
    }
}
